import "./globals.css";

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

//[ for better SEO ]

export const metadata = {
  title: "auth-google-next",
  description: "practice firebase auth",
};

// next.js convention for layout.js
// most importent is function peramitard. the peramitars should be a object. and also export as a default.
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>{children}</body>
    </html>
  );
}
